
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/pro/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/pro/noarch/repodata.json.bz2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2aede41e49b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)


Could not find conda environment: py37
You can list all discoverable environments with `conda info --envs`.

/u/alaa/.local/lib/python3.7/site-packages/ase/utils/__init__.py:41: FutureWarning: Please use atoms.cell.reciprocal()
  warnings.warn(warning)
